development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  database: seater_db
  username: nura
  password: nura


test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  database: test_seater_db
  username: nura
  password: nura


